---
version: 1
interactions:
- request:
    body: |
      {}
    form: {}
    headers:
      Content-Type:
      - application/json
      User-Agent:
      - google-api-go-client/0.5 go-cloud/blob/0.1.0
      X-Goog-Api-Client:
      - gl-go/1.12.0 gccl/20180226
    url: https://www.googleapis.com/storage/v1/b/go-cloud-blob-test-bucket/o/does-not-exist/rewriteTo/b/go-cloud-blob-test-bucket/o/blob-for-copying-dest?alt=json&prettyPrint=false&projection=full
    method: POST
  response:
    body: '{"error":{"errors":[{"domain":"global","reason":"notFound","message":"No
      such object: go-cloud-blob-test-bucket/does-not-exist","debugInfo":"com.google.net.rpc3.RpcException:
      cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND: No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat
      com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:144)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:301)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.rewrite(RewriteObject.java:200)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.handleRequestReceived(RewriteObject.java:193)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.handleRequestReceived(RewriteObject.java:47)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handleRequestReceived(RequestHandler.java:307)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:256)\n\tat
      com.google.cloud.bigstore.api.json.ObjectsDelegator.rewrite(ObjectsDelegator.java:124)\n\tat
      com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$4(RpcReceiver.java:202)\n\tat
      com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:253)\n\tat
      com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat
      com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:203)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat
      com.google.common.context.ContextRunnable.run(ContextRunnable.java:35)\n\tat
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat
      java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:291)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:299)\n\t...
      18 more\n\ncom.google.api.server.core.Fault: ImmutableErrorDefinition{base=NOT_FOUND,
      category=USER_ERROR, cause=null, debugInfo=com.google.net.rpc3.RpcException:
      cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND: No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat
      com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:144)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:301)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.rewrite(RewriteObject.java:200)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.handleRequestReceived(RewriteObject.java:193)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.handleRequestReceived(RewriteObject.java:47)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handleRequestReceived(RequestHandler.java:307)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:256)\n\tat
      com.google.cloud.bigstore.api.json.ObjectsDelegator.rewrite(ObjectsDelegator.java:124)\n\tat
      com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$4(RpcReceiver.java:202)\n\tat
      com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:253)\n\tat
      com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat
      com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:203)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat
      com.google.common.context.ContextRunnable.run(ContextRunnable.java:35)\n\tat
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat
      java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:291)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:299)\n\t...
      18 more\n, domain=global, extendedHelp=null, httpHeaders={}, httpStatus=notFound,
      internalReason=Reason{arguments={}, cause=null, code=gdata.CoreErrorDomain.NOT_FOUND,
      createdByBackend=true, debugMessage=com.google.net.rpc3.RpcException: cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:144)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:301)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.rewrite(RewriteObject.java:200)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.handleRequestReceived(RewriteObject.java:193)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.handleRequestReceived(RewriteObject.java:47)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handleRequestReceived(RequestHandler.java:307)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:256)\n\tat
      com.google.cloud.bigstore.api.json.ObjectsDelegator.rewrite(ObjectsDelegator.java:124)\n\tat
      com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$4(RpcReceiver.java:202)\n\tat
      com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:253)\n\tat
      com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat
      com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:203)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat
      com.google.common.context.ContextRunnable.run(ContextRunnable.java:35)\n\tat
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat
      java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:291)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:299)\n\t...
      18 more\n, errorProtoCode=NOT_FOUND, errorProtoDomain=gdata.CoreErrorDomain,
      filteredMessage=null, location=entity.destination_id.name, message=No such object:
      go-cloud-blob-test-bucket/does-not-exist, unnamedArguments=[]}, location=entity.destination_id.name,
      message=No such object: go-cloud-blob-test-bucket/does-not-exist, reason=notFound,
      rpcCode=404} No such object: go-cloud-blob-test-bucket/does-not-exist: com.google.net.rpc3.RpcException:
      cloud.bigstore.ResponseCode.ErrorCode::OBJECT_NOT_FOUND: No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat
      com.google.cloud.bigstore.common.BigstoreException.toRpc3Exception(BigstoreException.java:144)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:301)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.rewrite(RewriteObject.java:200)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.handleRequestReceived(RewriteObject.java:193)\n\tat
      com.google.cloud.bigstore.api.json.handlers.objects.RewriteObject.handleRequestReceived(RewriteObject.java:47)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handleRequestReceived(RequestHandler.java:307)\n\tat
      com.google.cloud.bigstore.api.json.framework.RequestHandler.handle(RequestHandler.java:256)\n\tat
      com.google.cloud.bigstore.api.json.ObjectsDelegator.rewrite(ObjectsDelegator.java:124)\n\tat
      com.google.cloud.bigstore.isolation.RpcReceiver.lambda$processRequestAsync$4(RpcReceiver.java:202)\n\tat
      com.google.cloud.bigstore.isolation.AsyncExecutor.lambda$submit$0(AsyncExecutor.java:253)\n\tat
      com.google.common.context.ContextRunnable.runInContext(ContextRunnable.java:50)\n\tat
      com.google.common.context.ContextRunnable$1.run(ContextRunnable.java:39)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:203)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContextNoUnref(GenericContextCallback.java:72)\n\tat
      com.google.tracing.GenericContextCallback.runInInheritedContext(GenericContextCallback.java:64)\n\tat
      com.google.common.context.ContextRunnable.run(ContextRunnable.java:35)\n\tat
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat
      java.lang.Thread.run(Thread.java:748)\nCaused by: com.google.cloud.bigstore.common.BigstoreException:
      No such object: go-cloud-blob-test-bucket/does-not-exist\n\tat com.google.cloud.bigstore.common.BigstoreException.throwOnError(BigstoreException.java:291)\n\tat
      com.google.cloud.bigstore.common.BigstoreException.throwRpc3OnError(BigstoreException.java:299)\n\t...
      18 more\n\n\tat com.google.api.server.core.ErrorCollector.toFault(ErrorCollector.java:54)\n\tat
      com.google.api.server.rest.adapter.rosy.RosyErrorConverter.toFault(RosyErrorConverter.java:67)\n\tat
      com.google.api.server.rest.adapter.rosy.RosyHandler$2.call(RosyHandler.java:259)\n\tat
      com.google.api.server.rest.adapter.rosy.RosyHandler$2.call(RosyHandler.java:239)\n\tat
      com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat
      com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)\n\tat
      com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1143)\n\tat
      com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:963)\n\tat
      com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:731)\n\tat
      com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat
      com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)\n\tat
      com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1143)\n\tat
      com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:963)\n\tat
      com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:731)\n\tat
      com.google.api.server.core.util.CallableFuture.run(CallableFuture.java:62)\n\tat
      com.google.api.server.thread.ThreadTrackers$ThreadTrackingRunnable.run(ThreadTrackers.java:126)\n\tat
      com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)\n\tat
      com.google.api.server.server.CommonModule$ContextCarryingExecutorService$1.runInContext(CommonModule.java:802)\n\tat
      com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)\n\tat
      io.grpc.Context.run(Context.java:565)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:204)\n\tat
      com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)\n\tat
      com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)\n\tat
      com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)\n\tat
      com.google.gse.internal.DispatchQueueImpl$WorkerThread.run(DispatchQueueImpl.java:403)\n"}],"code":404,"message":"No
      such object: go-cloud-blob-test-bucket/does-not-exist"}}'
    headers:
      Alt-Svc:
      - quic=":443"; ma=2592000; v="46,44,43,39"
      Content-Length:
      - "12487"
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Thu, 18 Apr 2019 16:58:13 GMT
      Server:
      - UploadServer
      Vary:
      - Origin
      - X-Origin
      X-Guploader-Customer:
      - apiary_cloudstorage_metadata
      X-Guploader-Request-Result:
      - agent_rejected
      X-Guploader-Upload-Result:
      - agent_rejected
      X-Guploader-Uploadid:
      - AEnB2UoUvPm1v2sVtzw1lfEHqlg4jnLXzb5QH7L7v5cU4rysrjdhFKEdwZs28qwEsSJLOqNWnt7lAwDbG0KG57UOE_NM7q4-5Q
    status: 404 Not Found
    code: 404
    duration: ""
